function Head() {
  return (
    <>
      <title>Demo App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
export default Head;
